### ISSUE TITLE
Having many erros when trying to update to RC2

### ISSUE THREAD

**Issue by MaherJendoubi** [rowanmiller/Demo-EFCore#4]
Hi Rowan,

Would you please update the demos to RC2?

Thanks.

**Comment by rowanmiller** [comment]
I was holding off until we shipped RTM, I will update the demos later this week.

**Comment by MaherJendoubi** [comment]
Thanks @rowanmiller

**Comment by MaherJendoubi** [comment]
@rowanmiller I'm looking forward to seeing the update for RTM :+1:

**Comment by MaherJendoubi** [comment]
@rowanmiller no update :(

**Comment by rowanmiller** [comment]
Projects are all updated to RTM now
