### ISSUE TITLE
Visual Studio and Asp.Net Core

### ISSUE THREAD

**Issue by MaherJendoubi** [rowanmiller/Demo-EFCore#5]
Hi Rowan,

What do you think about this thread please?
http://forums.asp.net/t/2099155.aspx?Visual+Studio+and+Asp+Net+Core

Thanks,
Maher

**Comment by rowanmiller** [comment]
I've replied to the thread. This repository is specifically for the EF Core Demo code. Please post future questions about EF in general to https://github.com/aspnet/EntityFramework.
