### ISSUE TITLE
EntityTypeBuilder.SeedData()

### ISSUE THREAD

**Issue by raphibolliger** [rowanmiller/Demo-EFCore#6]
@rowanmiller 
In my EF core project i can't use the SeedData() methode. Do I need a special NuGet package to have this methode available? I didn't find any documentation or code examples online for seed data generation. Is this feature actually available in EF Core?

Thanks for help.
Regards
Raphael

https://github.com/rowanmiller/Demo-EFCore/blob/fe9abececb6959df9d9d0d9f2382cf807f13e03e/CompletedSourceCode/SeedData/Program.cs#L29

**Comment by rowanmiller** [comment]
Could you follow up on the status of seed data on the EF repo (I've moved off the EF team now 😄) https://github.com/aspnet/EntityFrameworkCore
